name: flutter_easy
description: A common Flutter package.
version: 0.1.0
author: OctMon <octmon@qq.com>
homepage: https://github.com/OctMon/flutter_easy

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network request result
  session: ^0.3.5
  # https://github.com/OctMon/session

  # Generate RFC4122(v1,v4,v5) UUIDs
  uuid: ^2.0.2
  # https://github.com/Daegalus/dart-uuid

  # a pure flutter toast library
  oktoast: ^2.2.0
  # https://github.com/OpenFlutter/flutter_oktoast

  # A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^0.6.0
  # https://github.com/OpenFlutter/flutter_screenutil

  # Plugin that allow Flutter to read value from persistent storage or save value to persistent storage base on MMKV framework
  mmkv_flutter: ^1.0.10
  # https://github.com/OpenFlutter/mmkv_flutter

  # This Flutter plugin provides an API for querying information about an
  package_info: ^0.4.0+6
  # https://github.com/flutter/plugins/tree/master/packages/package_info

  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^1.1.1
  # https://github.com/renefloor/flutter_cached_network_image

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
